name: DiskUnlocker CI

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Build
      run: dotnet build
    - name: Publish framework-dependent
      run: dotnet publish -c Release -o publish src/DiskUnlocker/DiskUnlocker.csproj
    - name: Publish self-contained
      run: dotnet publish -c Release -o publish-selfcontained -r win-x64 --self-contained true src/DiskUnlocker/DiskUnlocker.csproj
    - name: Create ZIPs
      run: |
        mkdir zips
        cd publish
        Compress-Archive -Path * -DestinationPath ../zips/DiskUnlocker.zip
        cd ../publish-selfcontained
        Compress-Archive -Path * -DestinationPath ../zips/DiskUnlocker-selfcontained.zip
    - name: Upload to pipeline artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zips
        path: ./zips
        retention-days: 30
    - name: Upload DiskUnlocker.zip to release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./zips/DiskUnlocker.zip
        asset_name: DiskUnlocker.zip
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload DiskUnlocker-selfcontained.zip to release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./zips/DiskUnlocker-selfcontained.zip
        asset_name: DiskUnlocker-selfcontained.zip
        tag: ${{ github.ref }}
        overwrite: true
